# -*- coding: utf-8 -*-
"""Looksrare_analysis_questions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xi2cV1adw78HGdK1z2F5vjqUSz4sLAOC

Plot the number of trades over time (x-axis = time, y-axis = number of trades)
"""

import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import numpy as np

import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/bhemen/looksrare/main/data_gathering/data/looksrare_exchange_orders_clean.csv?token=GHSAT0AAAAAABWEC5S4WCFHLF4EDSPMUMUIYWATBJA")

trades = df.groupby(['timestamp']).size().to_frame('num_trades').reset_index()

trades.plot(kind = 'scatter', x ='timestamp', y='num_trades')

plt.show()

import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import numpy as np

import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/bhemen/looksrare/main/data_gathering/data/looksrare_exchange_orders_clean.csv?token=GHSAT0AAAAAABWEC5S5EOKDBRNDV4UNC7TQYWARGTQ")

df

"""Plot the trade volume over time (x-axis = time, y-axis = total amount of currency traded in USD or ETH)"""

import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import numpy as np

import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/bhemen/looksrare/main/data_gathering/data/looksrare_exchange_orders_clean.csv?token=GHSAT0AAAAAABWEC5S4WCFHLF4EDSPMUMUIYWATBJA")

df['cumulative_prices'] = df.price.cumsum()

df.plot(kind = 'scatter', x ='timestamp', y='cumulative_prices')

plt.show()

"""

Make a histogram of the number of sales per collection (x axis - number of sales, y axis - number of collections that have that many sales)"""

import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import numpy as np

import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/bhemen/looksrare/main/data_gathering/data/looksrare_exchange_orders_clean.csv?token=GHSAT0AAAAAABWEC5S4WCFHLF4EDSPMUMUIYWATBJA")
sales_counts = df.groupby(['collection']).size().to_frame('num_sales').reset_index()

sales_counts['frequency'] = sales_counts['num_sales'].value_counts()

sales_counts

sales_counts.hist('frequency')

"""Make a histogram of the number of trades per wallet address (x axis - number of sales, y axis - number of addresses that have that many trades)"""

import pandas as pd
import io
import requests
import matplotlib.pyplot as plt
import numpy as np

import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/bhemen/looksrare/main/data_gathering/data/looksrare_exchange_orders_clean.csv?token=GHSAT0AAAAAABWEC5S4WCFHLF4EDSPMUMUIYWATBJA")

df_sales_volumn = pd.DataFrame(df['collection'].value_counts())
df_sales_volumn = df_sales_volumn.reset_index()
df_sales_volumn.columns = ['contract_address', 'occurrence']

df_sales_volumn
df_sales_volumn.hist('occurrence', bins = 20)